model_list:
  - model_name: default
    litellm_params:
      model: os.environ/LITELLM_UPSTREAM_MODEL
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/OPENAI_API_BASE

  - model_name: gpt-5-nano
    litellm_params:
      model: os.environ/LITELLM_UPSTREAM_MODEL
      api_key: os.environ/OPENAI_API_KEY
      api_base: os.environ/OPENAI_API_BASE
